services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloud-ide-backend
    ports:
      - "${APP_PORT}:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: unless-stopped

  runner:
    build:
      context: ./runner
      dockerfile: Dockerfile
    image: python-runner:latest
    container_name: cloud-ide-runner-build
    command: ["python", "--version"]

networks:
  cloud-ide-network:
    driver: bridge